In [1]:
import pandas as pd
import yfinance as yf
from sqlalchemy import create_engine

DB_URL = "postgresql://admin:adminpassword@localhost:5432/brentprices_data"
engine = create_engine(DB_URL)

START_DATE = "2007-07-30"
END_DATE   = "2026-03-10"

TICKERS = {
    "BZ=F":     "brent_prices",
    "CL=F":     "wti_prices",
    "DX-Y.NYB": "dxy_prices",
    "GC=F":     "gold_prices",
}

In [ ]:
ticker = "BZ=F"
start_date = "2007-07-30"
end_date = "2026-03-06"

brent_data = yf.download(tickers=ticker, start=start_date, end=end_date, interval="1d")

if brent_data.empty:
    print("Data not retrieved.")
else:
    print(f"Retrieved records: {len(brent_data)}")
    display(brent_data.head())
    display(brent_data.tail())

[*********************100%***********************]  1 of 1 completed

Retrieved records: 4628

Price           Close       High        Low       Open Volume
Ticker           BZ=F       BZ=F       BZ=F       BZ=F   BZ=F
Date
2007-07-30  75.739998  76.529999  75.440002  75.849998   2575
2007-07-31  77.050003  77.169998  75.669998  75.699997   3513
2007-08-01  75.349998  77.059998  74.860001  77.000000   3930
2007-08-02  75.760002  76.209999  74.269997  75.220001   6180
2007-08-03  74.750000  76.000000  74.529999  75.389999   4387

Price           Close       High        Low       Open  Volume
Ticker           BZ=F       BZ=F       BZ=F       BZ=F    BZ=F
Date
2026-02-27  72.480003  72.989998  70.440002  70.500000   79435
2026-03-02  77.739998  82.110001  75.790001  77.000000  143671
2026-03-03  81.400002  85.050003  77.370003  78.050003  229556
2026-03-04  81.400002  84.449997  80.300003  81.900002  152390
2026-03-05  85.410004  86.279999  81.519997  82.430000  146018

In [6]:
db_url = "postgresql://admin:adminpassword@localhost:5432/brentprices_data"
engine = create_engine(db_url)

if isinstance(brent_data.columns, pd.MultiIndex):
    brent_data.columns = brent_data.columns.droplevel(1)

table_name = "brent_quotes"

brent_data.to_sql(name=table_name, con=engine, if_exists="replace", index=True, index_label="Date")

verification = pd.read_sql(f"SELECT COUNT(*) FROM {table_name}", engine)
print(f"Records in DB: {verification.iloc[0, 0]}")

Records in DB: 4628